development:
  adapter: postgresql
  encoding: utf8
  database: sample_app_development
  pool: 5
  username: revbox 
  password: r3Vb0x

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: sample_app_test
  pool: 5
  username: revbox
  password: r3Vb0x

production:
  adapter: postgresql
  encoding: utf8
  database: sample_app_production
  pool: 5
  username: revbox
  password: r3Vb0x
